name: Hank Quinlan, Horrible Cop
	markdown: kramdown
permalink: /blog/:year/:month/:day/:title

paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-sitemap

theme: jekyll-theme-time-machine